name = "staff-foreveryoung"
main = "public/_worker.js"
compatibility_date = "2024-03-20"
pages_build_output_dir = "./public"

[assets]
directory = "./public"
binding = "ASSETS"

[[d1_databases]]
binding = "DB"
database_name = "foreveryoung-db"
database_id = "4977069b-0252-40ab-895f-103ff41a6d22"